CREATE TABLE composer (id INTEGER PRIMARY KEY,
                       firstname VARCHAR(30),
                       surname VARCHAR(30),
                       imagefile BLOB);

INSERT INTO composer (firstname, surname, imagefile) VALUES
  ('Isaac', 'Albéniz', readfile('images/albeniz.png'));
INSERT INTO composer (firstname, surname, imagefile) VALUES
  ('Johann Sebastian', 'Bach', readfile('images/bach.png'));
INSERT INTO composer (firstname, surname, imagefile) VALUES
  ('Mili Alexejewitsch', 'Balakirew', readfile('images/balakirew.png'));
INSERT INTO composer (firstname, surname, imagefile) VALUES
  ('Ludwig van', 'Beethoven', readfile('images/beethoven.png'));
INSERT INTO composer (firstname, surname, imagefile) VALUES
  ('Alexander P.', 'Borodin', readfile('images/borodin.png'));
INSERT INTO composer (firstname, surname, imagefile) VALUES
  ('Johannes', 'Brahms', readfile('images/brahms.png'));
INSERT INTO composer (firstname, surname, imagefile) VALUES
  ('Friedrich', 'Burgmüller', readfile('images/burgmueller.png'));
INSERT INTO composer (firstname, surname, imagefile) VALUES
  ('Frédéric', 'Chopin', readfile('images/chopin.png'));
INSERT INTO composer (firstname, surname, imagefile) VALUES
  ('Claude', 'Debussy', readfile('images/debussy.png'));
INSERT INTO composer (firstname, surname, imagefile) VALUES
  ('Enrique', 'Granados', readfile('images/granados.png'));
INSERT INTO composer (firstname, surname, imagefile) VALUES
  ('Edvard', 'Grieg', readfile('images/grieg.png'));
INSERT INTO composer (firstname, surname, imagefile) VALUES
  ('Joseph', 'Haydn', readfile('images/haydn.png'));
INSERT INTO composer (firstname, surname, imagefile) VALUES
  ('Franz', 'Liszt', readfile('images/liszt.png'));
INSERT INTO composer (firstname, surname, imagefile) VALUES
  ('Felix', 'Mendelssohn Bartholdy', readfile('images/mendelssohn.png'));
INSERT INTO composer (firstname, surname, imagefile) VALUES
  ('Wolfgang Amadeus', 'Mozart', readfile('images/mozart.png'));
INSERT INTO composer (firstname, surname, imagefile) VALUES
  ('Modest', 'Mussorgski', readfile('images/mussorgski.png'));
INSERT INTO composer (firstname, surname, imagefile) VALUES
  ('Sergei Wassiljewitsch', 'Rachmaninow', readfile('images/rachmaninow.png'));
INSERT INTO composer (firstname, surname, imagefile) VALUES
  ('Franz', 'Schubert', readfile('images/schubert.png'));
INSERT INTO composer (firstname, surname, imagefile) VALUES
  ('Robert', 'Schumann', readfile('images/schumann.png'));
INSERT INTO composer (firstname, surname, imagefile) VALUES
  ('Peter', 'Tschaikowski', readfile('images/tschaikowski.png'));


CREATE TABLE composition (id INTEGER PRIMARY KEY,
                          composer_id INTEGER,
                          name VARCHAR(255),
                          duration INTEGER,
                          midifile BLOB);

INSERT INTO composition (name, composer_id, midifile) VALUES
    ( "España, Opus 165, Prélude",
      (SELECT id from composer WHERE surname='Albéniz'),
      readfile('BerndKrueger/Albeniz/alb_esp1.mid')),
    ( "España, Opus 165, Tango",
      (SELECT id from composer WHERE surname='Albéniz' ),
      readfile('BerndKrueger/Albeniz/alb_esp2.mid')),
    ( "España, Opus 165, Malagueña",
      (SELECT id from composer WHERE surname='Albéniz' ),
      readfile('BerndKrueger/Albeniz/alb_esp3.mid')),
    ( "España, Opus 165, Serenata",
      (SELECT id from composer WHERE surname='Albéniz'),
      readfile('BerndKrueger/Albeniz/alb_esp4.mid')),
    ( "España, Opus 165, Capricho Catalan",
      (SELECT id from composer WHERE surname='Albéniz' ),
      readfile('BerndKrueger/Albeniz/alb_esp5.mid')),
    ( "España, Opus 165, Zortzico",
      (SELECT id from composer WHERE surname='Albéniz' ),
      readfile('BerndKrueger/Albeniz/alb_esp6.mid')),

    ( "Präludium und Fuge in C-Dur BWV 846",
      (SELECT id from composer WHERE surname='Bach'),
      readfile('BerndKrueger/Bach/bach_846.mid')),
    ( "Präludium und Fuge in c-Moll BWV 847",
      (SELECT id from composer WHERE surname='Bach' ),
      readfile('BerndKrueger/Bach/bach_847.mid')),
    ( "Präludium und Fuge in D-Dur BWV 850",
      (SELECT id from composer WHERE surname='Bach' ),
      readfile('BerndKrueger/Bach/bach_850.mid')),

    ( "Islamei (Orientalische Fantasie) (1869)",
      (SELECT id from composer WHERE surname='Balakirew'),
      readfile('BerndKrueger/Balakirew/islamei.mid')),

    ( "Sonate Nr. 23 f-Moll (Appassionata), Opus 57, 1. Satz Allegro assai",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/appass_1.mid')),
    ( "Sonate Nr. 23 f-Moll (Appassionata), Opus 57, 2. Satz Andante con moto",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/appass_2.mid')),
    ( "Sonate Nr. 23 f-Moll (Appassionata), Opus 57, 3. Satz Allegro ma non troppo",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/appass_3.mid')),
    ( "Sonate Nr. 29 B-Dur (Hammerklavier), Opus 106, 1. Satz Allegro",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/beethoven_hammerklavier_1.mid')),
    ( "Sonate Nr. 29 B-Dur (Hammerklavier), Opus 106, 2. Satz Scherzo",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/beethoven_hammerklavier_2.mid')),
    ( "Sonate Nr. 29 B-Dur (Hammerklavier), Opus 106, 3. Satz Adagio sostenuto",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/beethoven_hammerklavier_3.mid')),
    ( "Sonate Nr. 29 B-Dur (Hammerklavier), Opus 106, 4. Satz Largo - Allegro",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/beethoven_hammerklavier_4.mid')),
    ( "Sonate Nr. 26 Es-Dur (Les Adieux), Opus 81a, 1. Satz Adagio",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/beethoven_les_adieux_1.mid')),
    ( "Sonate Nr. 26 Es-Dur (Les Adieux), Opus 81a, 2. Satz Andante espressivo",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/beethoven_les_adieux_2.mid')),
    ( "Sonate Nr. 26 Es-Dur (Les Adieux), Opus 81a, 3. Satz Vivacissimamente",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/beethoven_les_adieux_3.mid')),
    ( "Sonate Nr. 5 c-Moll, Opus 10/1, 1. Satz Allegro molto e con brio",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/beethoven_opus10_1.mid')),
    ( "Sonate Nr. 5 c-Moll, Opus 10/1, 2. Satz Adagio molto",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/beethoven_opus10_2.mid')),
    ( "Sonate Nr. 5 c-Moll, Opus 10/1, 3. Satz Prestissimo",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/beethoven_opus10_3.mid')),
    ( "Sonate Nr. 11 B-Dur, Opus 22, 1. Satz Allegro con brio",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/beethoven_opus22_1.mid')),
    ( "Sonate Nr. 11 B-Dur, Opus 22, 2. Satz Adagio con molta espressione",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/beethoven_opus22_2.mid')),
    ( "Sonate Nr. 11 B-Dur, Opus 22, 3. Satz Minuetto",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/beethoven_opus22_3.mid')),
    ( "Sonate Nr. 11 B-Dur, Opus 22, 4. Satz Rondo-Allegretto",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/beethoven_opus22_4.mid')),
    ( "Sonate Nr. 27 e-Moll, Opus 90, 1. Satz Mit Lebhaftigkeit und durchaus mit Empfindung und Ausdruck",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/beethoven_opus90_1.mid')),
    ( "Sonate Nr. 27 e-Moll, Opus 90, 2. Satz Nicht zu geschwind und sehr singbar vorgetragen",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/beethoven_opus90_2.mid')),
    ( "Für Elise",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/elise.mid')),
    ( "Sonate Nr. 14 cis-Moll (Mondscheinsonate), Opus 27/2, 1. Satz Adagio sostenuto",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/mond_1.mid')),
    ( "Sonate Nr. 14 cis-Moll (Mondscheinsonate), Opus 27/2, 2. Satz Allegretto",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/mond_2.mid')),
    ( "Sonate Nr. 14 cis-Moll (Mondscheinsonate), Opus 27/2, 3. Satz Presto agitato",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/mond_3.mid')),
    ( "Sonate Nr. 8 c-Moll (Pathetique), Opus 13, 1. Satz Grave - Allegro di molto e con brio",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/pathetique_1.mid')),
    ( "Sonate Nr. 8 c-Moll (Pathetique), Opus 13, 2. Satz Adagio cantabile",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/pathetique_2.mid')),
    ( "Sonate Nr. 8 c-Moll (Pathetique), Opus 13, 3. Satz Rondo allegro",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/pathetique_3.mid')),
    ( "Sonate Nr. 21 C-Dur (Waldstein), Opus 53, 1. Satz Allegro con brio",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/waldstein_1.mid')),
    ( "Sonate Nr. 21 C-Dur (Waldstein), Opus 53, 2. Satz Adagio molto",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/waldstein_2.mid')),
    ( "Sonate Nr. 21 C-Dur (Waldstein), Opus 53, 3. Satz Allegro moderato",
      (SELECT id from composer WHERE surname='Beethoven'),
      readfile('BerndKrueger/Beethoven/waldstein_3.mid')),

    ( "Im Kloster - Andante religioso",
      (SELECT id from composer WHERE surname='Borodin'),
      readfile('BerndKrueger/Borodin/bor_ps1.mid')),
    ( "Intermezzo - Tempo di minuetto",
      (SELECT id from composer WHERE surname='Borodin'),
      readfile('BerndKrueger/Borodin/bor_ps2.mid')),
    ( "Mazurka - Allegro",
      (SELECT id from composer WHERE surname='Borodin'),
      readfile('BerndKrueger/Borodin/bor_ps3.mid')),
    ( "Mazurka - Allegretto",
      (SELECT id from composer WHERE surname='Borodin'),
      readfile('BerndKrueger/Borodin/bor_ps4.mid')),
    ( "Réverie - Andante",
      (SELECT id from composer WHERE surname='Borodin'),
      readfile('BerndKrueger/Borodin/bor_ps5.mid')),
    ( "Serenade - Allegretto",
      (SELECT id from composer WHERE surname='Borodin'),
      readfile('BerndKrueger/Borodin/bor_ps6.mid')),
    ( "Nocturne - Andantino",
      (SELECT id from composer WHERE surname='Borodin'),
      readfile('BerndKrueger/Borodin/bor_ps7.mid')),

    ( "Sonate C-Dur, Opus 1, 1. Satz Allegro",
      (SELECT id from composer WHERE surname='Brahms'),
      readfile('BerndKrueger/Brahms/brahms_opus1_1.mid')),
    ( "Sonate C-Dur, Opus 1, 2. Satz Andante",
      (SELECT id from composer WHERE surname='Brahms'),
      readfile('BerndKrueger/Brahms/brahms_opus1_2.mid')),
    ( "Sonate C-Dur, Opus 1, 3. Satz Scherzo",
      (SELECT id from composer WHERE surname='Brahms'),
      readfile('BerndKrueger/Brahms/brahms_opus1_3.mid')),
    ( "Sonate C-Dur, Opus 1, 4. Satz Finale - Allegro con fuoco",
      (SELECT id from composer WHERE surname='Brahms'),
      readfile('BerndKrueger/Brahms/brahms_opus1_4.mid')),
    ( "7 Fantasien, Opus 116, Nr.2 Intermezzo",
      (SELECT id from composer WHERE surname='Brahms'),
      readfile('BerndKrueger/Brahms/br_im2.mid')),
    ( "7 Fantasien, Opus 116, Nr.5 Intermezzo",
      (SELECT id from composer WHERE surname='Brahms'),
      readfile('BerndKrueger/Brahms/br_im5.mid')),
    ( "7 Fantasien, Opus 116, Nr.6 Intermezzo",
      (SELECT id from composer WHERE surname='Brahms'),
      readfile('BerndKrueger/Brahms/BR_IM6.mid')),
    ( "3 Intermezzi, Opus 117, Nr.1 Andante moderato",
      (SELECT id from composer WHERE surname='Brahms'),
      readfile('BerndKrueger/Brahms/brahms_opus117_1.mid')),
    ( "3 Intermezzi, Opus 117, Nr.2 Andante moderato",
      (SELECT id from composer WHERE surname='Brahms'),
      readfile('BerndKrueger/Brahms/brahms_opus117_2.mid')),
    ( "4 Klavierstücke, Opus 119, Rhapsodie Allegro risoluto",
      (SELECT id from composer WHERE surname='Brahms'),
      readfile('BerndKrueger/Brahms/br_rhap.mid')),

    ( "Etüden, Opus 109, Die Perlen - Moderato",
      (SELECT id from composer WHERE surname='Burgmüller'),
      readfile('BerndKrueger/Burgmueller/burg_perlen.mid')),
    ( "Etüden, Opus 109, Die Quelle - Andante grazioso",
      (SELECT id from composer WHERE surname='Burgmüller'),
      readfile('BerndKrueger/Burgmueller/burg_quelle.mid')),
    ( "Etüden, Opus 109, Agitato - Allegro vivace",
      (SELECT id from composer WHERE surname='Burgmüller'),
      readfile('BerndKrueger/Burgmueller/burg_agitato.mid')),
    ( "Etüden, Opus 109, Geschwindigkeit - Vivo",
      (SELECT id from composer WHERE surname='Burgmüller'),
      readfile('BerndKrueger/Burgmueller/burg_geschwindigkeit.mid')),
    ( "Etüden, Opus 109, Erwachen im Walde - Allegro",
      (SELECT id from composer WHERE surname='Burgmüller'),
      readfile('BerndKrueger/Burgmueller/burg_erwachen.mid')),
    ( "Etüden, Opus 109, Gewitter - Allegro",
      (SELECT id from composer WHERE surname='Burgmüller'),
      readfile('BerndKrueger/Burgmueller/burg_gewitter.mid')),
    ( "Etüden, Opus 109, Die Sylphen - Vivo",
      (SELECT id from composer WHERE surname='Burgmüller'),
      readfile('BerndKrueger/Burgmueller/burg_sylphen.mid')),
    ( "Etüden, Opus 109, Trennung - Allegro vivace",
      (SELECT id from composer WHERE surname='Burgmüller'),
      readfile('BerndKrueger/Burgmueller/burg_trennung.mid')),
    ( "Etüden, Opus 109, Spinnerlied - Allegro moderato",
      (SELECT id from composer WHERE surname='Burgmüller'),
      readfile('BerndKrueger/Burgmueller/burg_spinnerlied.mid')),

    ( "5 Mazurken, Opus 7, Nr. 1 Vivace",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn_op7_1.mid')),
    ( "5 Mazurken, Opus 7, Nr. 2 Viva ma non troppo",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn_op7_2.mid')),
    ( "Etüden, Opus 10, Nr. 1 - Allegro",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn_op10_e01.mid')),
    ( "Etüden, Opus 10, Nr. 5 - Schwarze-Tasten-Etüde - Vivace",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn_op10_e05.mid')),
    ( "Etüden, Opus 10, Nr. 12 - Revolutionsetüde - Allegro con fuoco",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn_op10_e12.mid')),
    ( "Grande Valse Brillante, Opus 18, Grande Valse Brillante - Vivo",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chp_op18.mid')),
    ( "Ballade g-Moll, Opus 23, Ballade Largo - Moderato",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn_op23.mid')),
    ( "Etüden, Opus 25, Nr. 1 - Harfenetüde - Allegro sostenuto",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn_op25_e1.mid')),
    ( "Etüden, Opus 25, Nr. 2 - Presto",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn_op25_e2.mid')),
    ( "Etüden, Opus 25, Nr. 3 - Allegro",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn_op25_e3.mid')),
    ( "Etüden, Opus 25, Nr. 4 - Agitato",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn_op25_e4.mid')),
    ( "Etüden, Opus 25, Nr. 11 - Sturmetüde - Lento - Allegro con brio",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn_op25_e11.mid')),
    ( "Etüden, Opus 25, Nr. 12 - Allegro molto con fuoco",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn_op25_e12.mid')),
    ( "2 Nocturnes, Opus 27, Nr. 1 - Larghetto",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn_op27_1.mid')),
    ( "2 Nocturnes, Opus 27, Nr. 2 - Lento sostenuto",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn_op27_2.mid')),
    ( "Préludes, Opus 28, Nr. 1 - Agitato",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn-p1.mid')),
    ( "Préludes, Opus 28, Nr. 2 - Lento",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn-p2.mid')),
    ( "Préludes, Opus 28, Nr. 3 - Vivace",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn-p3.mid')),
    ( "Préludes, Opus 28, Nr. 4 - Largo",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn-p4.mid')),
    ( "Préludes, Opus 28, Nr. 5 - Molto allegro",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn-p5.mid')),
    ( "Préludes, Opus 28, Nr. 6 - Assai lento",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn-p6.mid')),
    ( "Préludes, Opus 28, Nr. 7 - Andantino",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn-p7.mid')),
    ( "Préludes, Opus 28, Nr. 8 - Molto agitato",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn-p8.mid')),
    ( "Préludes, Opus 28, Nr. 9 - Largo",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn-p9.mid')),
    ( "Préludes, Opus 28, Nr. 10 - 	Molto allegro",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn-p10.mid')),
    ( "Préludes, Opus 28, Nr. 11 - Vivace",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn-p11.mid')),
    ( "Préludes, Opus 28, Nr. 12 - Presto",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn-p12.mid')),
    ( "Préludes, Opus 28, Nr. 13 - Lento",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn-p13.mid')),
    ( "Préludes, Opus 28, Nr. 14 - Allegro",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn-p14.mid')),
    ( "Préludes, Opus 28, Nr. 15 - Regentropfenprélude - Sostenuto",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn-p15.mid')),
    ( "Préludes, Opus 28, Nr. 16 - Presto con fuoco",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn-p16.mid')),
    ( "Préludes, Opus 28, Nr. 17 - Allegretto",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn-p17.mid')),
    ( "Préludes, Opus 28, Nr. 18 - Molto allegro",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn-p18.mid')),
    ( "Préludes, Opus 28, Nr. 19 - Vivace",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn-p19.mid')),
    ( "Préludes, Opus 28, Nr. 20 - Largo",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn-p20.mid')),
    ( "Préludes, Opus 28, Nr. 21 - Cantabile",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn-p21.mid')),
    ( "Préludes, Opus 28, Nr. 22 - Molto agitato",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn-p22.mid')),
    ( "Préludes, Opus 28, Nr. 23 - Moderato",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn-p23.mid')),
    ( "Préludes, Opus 28, Nr. 24 - Allegro appassionato",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn-p24.mid')),
    ( "Scherzo b-Moll, Opus 31, Scherzo - Presto",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chp_op31.mid')),
    ( "4 Mazurken, Opus 33, Nr. 2 - Vivace",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn_op33_2.mid')),
    ( "4 Mazurken, Opus 33, Nr. 4",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn_op33_4.mid')),
    ( "Klaviersonate Nr. 2 b-Moll, Opus 35, 1. Satz Grave - Doppio movimento",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn_op35_1.mid')),
    ( "Klaviersonate Nr. 2 b-Moll, Opus 35, 2. Satz Scherzo",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn_op35_2.mid')),
    ( "Klaviersonate Nr. 2 b-Moll, Opus 35, 3. Satz Marche funèbre",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn_op35_3.mid')),
    ( "Klaviersonate Nr. 2 b-Moll, Opus 35, 4. Satz Presto",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn_op35_4.mid')),
    ( "Polonaise As-Dur, Opus 53, Polonaise - Maestoso",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn_op53.mid')),
    ( "Fantaisie-Impromptu, Opus 66, Allegro agitato",
      (SELECT id from composer WHERE surname='Chopin'),
      readfile('BerndKrueger/Chopin/chpn_op66.mid')),

    ( "Suite bergamasque, Prélude, Moderato (tempo rubato)",
      (SELECT id from composer WHERE surname='Debussy'),
      readfile('BerndKrueger/Debussy/deb_prel.mid')),
    ( "Suite bergamasque, Menuet, Andantino",
      (SELECT id from composer WHERE surname='Debussy'),
      readfile('BerndKrueger/Debussy/deb_menu.mid')),
    ( "Suite bergamasque, Clair de Lune, Andante très expressif",
      (SELECT id from composer WHERE surname='Debussy'),
      readfile('BerndKrueger/Debussy/DEB_CLAI.mid')),
    ( "Suite bergamasque, Passepied, Allegretto ma non troppo",
      (SELECT id from composer WHERE surname='Debussy'),
      readfile('BerndKrueger/Debussy/DEB_PASS.mid')),
    ( "Children's Corner, I. Doctor Gradus ad Parnassum, Modérément animé",
      (SELECT id from composer WHERE surname='Debussy'),
      readfile('BerndKrueger/Debussy/debussy_cc_1.mid')),
    ( "Children's Corner, Jimbo's Lullaby, Assez modéré",
      (SELECT id from composer WHERE surname='Debussy'),
      readfile('BerndKrueger/Debussy/debussy_cc_2.mid')),
    ( "Children's Corner, Serenade of the Doll, Allegretto ma non troppo",
      (SELECT id from composer WHERE surname='Debussy'),
      readfile('BerndKrueger/Debussy/debussy_cc_3.mid')),
    ( "Children's Corner, The snow is dancing, Modérément animé",
      (SELECT id from composer WHERE surname='Debussy'),
      readfile('BerndKrueger/Debussy/debussy_cc_4.mid')),
    ( "Children's Corner, The little Shepherd, Très modéré",
      (SELECT id from composer WHERE surname='Debussy'),
      readfile('BerndKrueger/Debussy/debussy_cc_5.mid')),
    ( "Children's Corner, Golli's cake walk, Allegro giusto",
      (SELECT id from composer WHERE surname='Debussy'),
      readfile('BerndKrueger/Debussy/debussy_cc_6.mid')),

    ( "Danzas españolas, Nr. 2 - Oriental, Andante",
      (SELECT id from composer WHERE surname='Granados'),
      readfile('BerndKrueger/Granados/gra_esp_2.mid')),
    ( "Danzas españolas, Nr. 3 - Zarabanda, Energico",
      (SELECT id from composer WHERE surname='Granados'),
      readfile('BerndKrueger/Granados/gra_esp_3.mid')),
    ( "Danzas españolas, No. 4 - Villanesca, Allegretto, alla pastorale",
      (SELECT id from composer WHERE surname='Granados'),
      readfile('BerndKrueger/Granados/gra_esp_4.mid')),

    ( "Lyrische Stücke Heft I, Opus 12, Nr. 2 - Valse - Allegro moderato",
      (SELECT id from composer WHERE surname='Grieg'),
      readfile('BerndKrueger/Grieg/grieg_walzer.mid')),
    ( "Lyrische Stücke Heft I, Opus 12, Nr. 3 - Wächterlied - Molto andante e simplice",
      (SELECT id from composer WHERE surname='Grieg'),
      readfile('BerndKrueger/Grieg/grieg_waechter.mid')),
    ( "Lyrische Stücke Heft I, Opus 12, Nr. 4 - Elfentanz - Molto allegro e sempre staccato",
      (SELECT id from composer WHERE surname='Grieg'),
      readfile('BerndKrueger/Grieg/grieg_elfentanz.mid')),
    ( "Lyrische Stücke Heft II, Opus 38, Nr. 1 - Berceuse - Allegretto tranquillo",
      (SELECT id from composer WHERE surname='Grieg'),
      readfile('BerndKrueger/Grieg/grieg_berceuse.mid')),
    ( "Lyrische Stücke Heft II, Opus 38, Nr. 4 - Halling - Allegro marcato",
      (SELECT id from composer WHERE surname='Grieg'),
      readfile('BerndKrueger/Grieg/grieg_halling.mid')),
    ( "Lyrische Stücke Heft III, Opus 43, Nr. 1 - Schmetterling - Allegro grazioso",
      (SELECT id from composer WHERE surname='Grieg'),
      readfile('BerndKrueger/Grieg/grieg_butterfly.mid')),
    ( "Lyrische Stücke Heft III, Opus 43, Nr. 2 - Einsamer Wanderer - Allegro semplice",
      (SELECT id from composer WHERE surname='Grieg'),
      readfile('BerndKrueger/Grieg/grieg_wanderer.mid')),
    ( "Lyrische Stücke Heft III, Opus 43, Nr. 4 - Vöglein - Allegro leggiero",
      (SELECT id from composer WHERE surname='Grieg'),
      readfile('BerndKrueger/Grieg/grieg_voeglein.mid')),
    ( "Lyrische Stücke Heft III, Opus 43, Nr. 6 - An den Frühling - Allegro appassionato",
      (SELECT id from composer WHERE surname='Grieg'),
      readfile('BerndKrueger/Grieg/grieg_spring.mid')),
    ( "Lyrische Stücke Heft IV, Opus 47, Nr. 2 - Albumblatt - Allegro vivace e grazioso",
      (SELECT id from composer WHERE surname='Grieg'),
      readfile('BerndKrueger/Grieg/grieg_album.mid')),
    ( "Lyrische Stücke Heft V, Opus 54, Nr. 2 - Norwegischer Bauernmarsch - Allegretto marcato",
      (SELECT id from composer WHERE surname='Grieg'),
      readfile('BerndKrueger/Grieg/grieg_march.mid')),
    ( "Lyrische Stücke Heft V, Opus 54, Nr. 3 - Zug der Zwerge - Allegro moderato",
      (SELECT id from composer WHERE surname='Grieg'),
      readfile('BerndKrueger/Grieg/grieg_zwerge.mid')),
    ( "Lyrische Stücke Heft VII, Opus 62, Nr. 4 - Bächlein - Allegro leggiore",
      (SELECT id from composer WHERE surname='Grieg'),
      readfile('BerndKrueger/Grieg/grieg_brooklet.mid')),
    ( "Lyrische Stücke Heft VIII, Opus 65, Nr. 6 - Hochzeitstag auf Troldhaugen - Tempo di Marcia un poco vivace",
      (SELECT id from composer WHERE surname='Grieg'),
      readfile('BerndKrueger/Grieg/grieg_wedding.mid')),
    ( "Lyrische Stücke Heft X, Opus 71, Nr. 1 - Es war einmal - Andante con moto",
      (SELECT id from composer WHERE surname='Grieg'),
      readfile('BerndKrueger/Grieg/grieg_once_upon_a_time.mid')),
    ( "Lyrische Stücke Heft X, Opus 71, Nr. 3 - Kobold - Tempo di Marcia un poco vivace",
      (SELECT id from composer WHERE surname='Grieg'),
      readfile('BerndKrueger/Grieg/grieg_kobold.mid')),

    ( "Klaviersonate in C-Dur, Hoboken XVI:7, 1. Satz Allegro moderato",
      (SELECT id from composer WHERE surname='Haydn'),
      readfile('BerndKrueger/Haydn/haydn_7_1.mid')),
    ( "Klaviersonate in C-Dur, Hoboken XVI:7, 2. Satz Menuett",
      (SELECT id from composer WHERE surname='Haydn'),
      readfile('BerndKrueger/Haydn/haydn_7_2.mid')),
    ( "Klaviersonate in C-Dur, Hoboken XVI:7, 3. Satz Finale",
      (SELECT id from composer WHERE surname='Haydn'),
      readfile('BerndKrueger/Haydn/haydn_7_3.mid')),
    ( "Klaviersonate in G-Dur, Hoboken XVI:8, 1. Satz Allegro",
      (SELECT id from composer WHERE surname='Haydn'),
      readfile('BerndKrueger/Haydn/haydn_8_1.mid')),
    ( "Klaviersonate in G-Dur, Hoboken XVI:8, 2. Satz Menuett",
      (SELECT id from composer WHERE surname='Haydn'),
      readfile('BerndKrueger/Haydn/haydn_8_2.mid')),
    ( "Klaviersonate in G-Dur, Hoboken XVI:8, 3. Satz Andante",
      (SELECT id from composer WHERE surname='Haydn'),
      readfile('BerndKrueger/Haydn/haydn_8_3.mid')),
    ( "Klaviersonate in G-Dur, Hoboken XVI:8, 4. Satz Andante",
      (SELECT id from composer WHERE surname='Haydn'),
      readfile('BerndKrueger/Haydn/haydn_8_4.mid')),
    ( "Klaviersonate in F-Dur, Hoboken XVI:9, 1. Satz Allegro",
      (SELECT id from composer WHERE surname='Haydn'),
      readfile('BerndKrueger/Haydn/haydn_9_1.mid')),
    ( "Klaviersonate in F-Dur, Hoboken XVI:9, 2. Satz Allegro",
      (SELECT id from composer WHERE surname='Haydn'),
      readfile('BerndKrueger/Haydn/haydn_9_2.mid')),
    ( "Klaviersonate in F-Dur, Hoboken XVI:9, 3. Satz Scherzo",
      (SELECT id from composer WHERE surname='Haydn'),
      readfile('BerndKrueger/Haydn/haydn_9_3.mid')),
    ( "Klaviersonate in D-Dur, Hoboken XVI:33, 1. Satz Allegro",
      (SELECT id from composer WHERE surname='Haydn'),
      readfile('BerndKrueger/Haydn/haydn_33_1.mid')),
    ( "Klaviersonate in D-Dur, Hoboken XVI:33, 2. Satz Adagio",
      (SELECT id from composer WHERE surname='Haydn'),
      readfile('BerndKrueger/Haydn/haydn_33_2.mid')),
    ( "Klaviersonate in D-Dur, Hoboken XVI:33, 3. Satz Tempo di Menuet",
      (SELECT id from composer WHERE surname='Haydn'),
      readfile('BerndKrueger/Haydn/haydn_33_3.mid')),
    ( "Klaviersonate in C-Dur, Hoboken XVI:35, 1. Satz Allegro con brio",
      (SELECT id from composer WHERE surname='Haydn'),
      readfile('BerndKrueger/Haydn/haydn_35_1.mid')),
    ( "Klaviersonate in C-Dur, Hoboken XVI:35, 2. Satz Adagio",
      (SELECT id from composer WHERE surname='Haydn'),
      readfile('BerndKrueger/Haydn/haydn_35_2.mid')),
    ( "Klaviersonate in C-Dur, Hoboken XVI:35, 3. Satz Finale Allegro",
      (SELECT id from composer WHERE surname='Haydn'),
      readfile('BerndKrueger/Haydn/haydn_35_3.mid')),
    ( "Klaviersonate in G-Dur, Hoboken XVI:40, 1. Satz Allegro e innocente",
      (SELECT id from composer WHERE surname='Haydn'),
      readfile('BerndKrueger/Haydn/hay_40_1.mid')),
    ( "Klaviersonate in G-Dur, Hoboken XVI:40, 2. Satz Presto",
      (SELECT id from composer WHERE surname='Haydn'),
      readfile('BerndKrueger/Haydn/hay_40_2.mid')),
    ( "Klaviersonate in As-Dur, Hoboken XVI:43, 1. Satz Moderato",
      (SELECT id from composer WHERE surname='Haydn'),
      readfile('BerndKrueger/Haydn/haydn_43_1.mid')),
    ( "Klaviersonate in As-Dur, Hoboken XVI:43, 2. Satz Menuet",
      (SELECT id from composer WHERE surname='Haydn'),
      readfile('BerndKrueger/Haydn/haydn_43_2.mid')),
    ( "Klaviersonate in As-Dur, Hoboken XVI:43, 3. Satz Rondo Presto",
      (SELECT id from composer WHERE surname='Haydn'),
      readfile('BerndKrueger/Haydn/haydn_43_3.mid')),

    ( "Reminiscences de Don Juan - Fantasie über Mozarts Don Giovanni",
      (SELECT id from composer WHERE surname='Liszt'),
      readfile('BerndKrueger/Liszt/liz_donjuan.mid')),
    ( "Liebesträume, Nr. 3 Poco Allegro con affetto",
      (SELECT id from composer WHERE surname='Liszt'),
      readfile('BerndKrueger/Liszt/liz_liebestraum.mid')),
    ( "Grandes Etudes de Paganini, Nr. 1 Andante - Non troppo lento",
      (SELECT id from composer WHERE surname='Liszt'),
      readfile('BerndKrueger/Liszt/liz_et1.mid')),
    ( "Grandes Etudes de Paganini, Nr. 2 Andante - Andantino capriccioso",
      (SELECT id from composer WHERE surname='Liszt'),
      readfile('BerndKrueger/Liszt/liz_et2.mid')),
    ( "Grandes Etudes de Paganini, Nr. 3 - La Campanella, Allegretto",
      (SELECT id from composer WHERE surname='Liszt'),
      readfile('BerndKrueger/Liszt/liz_et3.mid')),
    ( "Grandes Etudes de Paganini, Nr. 4 Vivo",
      (SELECT id from composer WHERE surname='Liszt'),
      readfile('BerndKrueger/Liszt/liz_et4.mid')),
    ( "Grandes Etudes de Paganini, Nr. 5 Allegretto",
      (SELECT id from composer WHERE surname='Liszt'),
      readfile('BerndKrueger/Liszt/liz_et5.mid')),
    ( "Grandes Etudes de Paganini, Nr. 6 Quasi presto",
      (SELECT id from composer WHERE surname='Liszt'),
      readfile('BerndKrueger/Liszt/liz_et6.mid')),
    ( "Études d'exécution transcendante, Nr. 4 - Mazeppa, Allegro",
      (SELECT id from composer WHERE surname='Liszt'),
      readfile('BerndKrueger/Liszt/liz_et_trans4.mid')),
    ( "Études d'exécution transcendante, Nr. 5 - Irrlichter, Allegretto",
      (SELECT id from composer WHERE surname='Liszt'),
      readfile('BerndKrueger/Liszt/liz_et_trans5.mid')),
    ( "Études d'exécution transcendante, Nr. 8 - Wilde Jagd, Presto furioso",
      (SELECT id from composer WHERE surname='Liszt'),
      readfile('BerndKrueger/Liszt/liz_et_trans8.mid')),
    ( "19 Ungarische Rhapsodien, Nr. 2, Lento a capriccio",
      (SELECT id from composer WHERE surname='Liszt'),
      readfile('BerndKrueger/Liszt/liz_rhap02.mid')),
    ( "19 Ungarische Rhapsodien, Nr. 9 - Pesther Karneval, Moderato",
      (SELECT id from composer WHERE surname='Liszt'),
      readfile('BerndKrueger/Liszt/liz_rhap09.mid')),
    ( "19 Ungarische Rhapsodien, Nr. 10, Preludio",
      (SELECT id from composer WHERE surname='Liszt'),
      readfile('BerndKrueger/Liszt/liz_rhap10.mid')),
    ( "19 Ungarische Rhapsodien, Nr. 12, Mesto",
      (SELECT id from composer WHERE surname='Liszt'),
      readfile('BerndKrueger/Liszt/liz_rhap12.mid')),
    ( "19 Ungarische Rhapsodien, Nr. 15 - Rákóczy-Marsch, Allegro animato - Tempo di Marcia animato",
      (SELECT id from composer WHERE surname='Liszt'),
      readfile('BerndKrueger/Liszt/liz_rhap15.mid')),

    ( "Lieder ohne Worte Heft 1, Opus 19, Nr. 1 - Andante con moto",
      (SELECT id from composer WHERE surname='Mendelssohn Bartholdy'),
      readfile('BerndKrueger/Mendelssohn/mendel_op19_1.mid')),
    ( "Lieder ohne Worte Heft 1, Opus 19, Nr. 2 - Andante expressivo",
      (SELECT id from composer WHERE surname='Mendelssohn Bartholdy'),
      readfile('BerndKrueger/Mendelssohn/mendel_op19_2.mid')),
    ( "Lieder ohne Worte Heft 1, Opus 19, Nr. 3 - Molto Allegro e vivace",
      (SELECT id from composer WHERE surname='Mendelssohn Bartholdy'),
      readfile('BerndKrueger/Mendelssohn/mendel_op19_3.mid')),
    ( "Lieder ohne Worte Heft 1, Opus 19, Nr. 4 - Moderato",
      (SELECT id from composer WHERE surname='Mendelssohn Bartholdy'),
      readfile('BerndKrueger/Mendelssohn/mendel_op19_4.mid')),
    ( "Lieder ohne Worte Heft 1, Opus 19, Nr. 5 - Piano agitato",
      (SELECT id from composer WHERE surname='Mendelssohn Bartholdy'),
      readfile('BerndKrueger/Mendelssohn/mendel_op19_5.mid')),
    ( "Lieder ohne Worte Heft 1, Opus 19, Nr. 6 - Venetianisches Gondellied - Andante sostenuto",
      (SELECT id from composer WHERE surname='Mendelssohn Bartholdy'),
      readfile('BerndKrueger/Mendelssohn/mendel_op19_6.mid')),
    ( "Lieder ohne Worte Heft 2, Opus 30, Nr. 1 - Andante espressivo",
      (SELECT id from composer WHERE surname='Mendelssohn Bartholdy'),
      readfile('BerndKrueger/Mendelssohn/mendel_op30_1.mid')),
    ( "Lieder ohne Worte Heft 2, Opus 30, Nr. 2 - Allegro di molto",
      (SELECT id from composer WHERE surname='Mendelssohn Bartholdy'),
      readfile('BerndKrueger/Mendelssohn/mendel_op30_2.mid')),
    ( "Lieder ohne Worte Heft 2, Opus 30, Nr. 3 - Adagio non troppo",
      (SELECT id from composer WHERE surname='Mendelssohn Bartholdy'),
      readfile('BerndKrueger/Mendelssohn/mendel_op30_3.mid')),
    ( "Lieder ohne Worte Heft 2, Opus 30, Nr. 4 - Agitato e con fuoco",
      (SELECT id from composer WHERE surname='Mendelssohn Bartholdy'),
      readfile('BerndKrueger/Mendelssohn/mendel_op30_4.mid')),
    ( "Lieder ohne Worte Heft 2, Opus 30, Nr. 5 - Andante grazioso",
      (SELECT id from composer WHERE surname='Mendelssohn Bartholdy'),
      readfile('BerndKrueger/Mendelssohn/mendel_op30_5.mid')),
    ( "Lieder ohne Worte Heft 4, Opus 53, Nr. 5 - Volkslied - Allegro con fuoco",
      (SELECT id from composer WHERE surname='Mendelssohn Bartholdy'),
      readfile('BerndKrueger/Mendelssohn/mendel_op53_5.mid')),
    ( "Lieder ohne Worte Heft 5, Opus 62, Nr. 3 - Trauermarsch - Andante maestoso",
      (SELECT id from composer WHERE surname='Mendelssohn Bartholdy'),
      readfile('BerndKrueger/Mendelssohn/mendel_op62_3.mid')),
    ( "Lieder ohne Worte Heft 5, Opus 62, Nr. 4 - Morgenlied - Allegro con anima",
      (SELECT id from composer WHERE surname='Mendelssohn Bartholdy'),
      readfile('BerndKrueger/Mendelssohn/mendel_op62_4.mid')),
    ( "Lieder ohne Worte Heft 5, Opus 62, Nr. 5 - Venetianisches Gondellied - Andante con moto",
      (SELECT id from composer WHERE surname='Mendelssohn Bartholdy'),
      readfile('BerndKrueger/Mendelssohn/mendel_op62_5.mid')),

    ( "Sonate Nr. 8 D-Dur, KV 311, 1. Satz - Allegro con spirito",
      (SELECT id from composer WHERE surname='Mozart'),
      readfile('BerndKrueger/Mozart/mz_311_1.mid')),
    ( "Sonate Nr. 8 D-Dur, KV 311, 2. Satz - Andantino con espressione",
      (SELECT id from composer WHERE surname='Mozart'),
      readfile('BerndKrueger/Mozart/mz_311_2.mid')),
    ( "Sonate Nr. 8 D-Dur, KV 311, 3. Satz - Rondo Allegro",
      (SELECT id from composer WHERE surname='Mozart'),
      readfile('BerndKrueger/Mozart/mz_311_3.mid')),
    ( "Sonate Nr. 10 C-Dur, KV 330, 1. Satz - Allegro moderato",
      (SELECT id from composer WHERE surname='Mozart'),
      readfile('BerndKrueger/Mozart/mz_330_1.mid')),
    ( "Sonate Nr. 10 C-Dur, KV 330, 2. Satz - Andante cantabile",
      (SELECT id from composer WHERE surname='Mozart'),
      readfile('BerndKrueger/Mozart/mz_330_2.mid')),
    ( "Sonate Nr. 10 C-Dur, KV 330, 3. Satz - Allegretto",
      (SELECT id from composer WHERE surname='Mozart'),
      readfile('BerndKrueger/Mozart/mz_330_3.mid')),
    ( "Sonate Nr. 11 A-Dur (Alla Turca) , KV 331, 1. Satz - Andante grazioso",
      (SELECT id from composer WHERE surname='Mozart'),
      readfile('BerndKrueger/Mozart/mz_331_1.mid')),
    ( "Sonate Nr. 11 A-Dur (Alla Turca) , KV 331, 2. Satz - Allegro moderato",
      (SELECT id from composer WHERE surname='Mozart'),
      readfile('BerndKrueger/Mozart/mz_331_2.mid')),
    ( "Sonate Nr. 11 A-Dur (Alla Turca) , KV 331, 3. Satz - Allegro",
      (SELECT id from composer WHERE surname='Mozart'),
      readfile('BerndKrueger/Mozart/mz_331_3.mid')),
    ( "Sonate Nr. 12 F-Dur, KV 332, 1. Satz - Allegro",
      (SELECT id from composer WHERE surname='Mozart'),
      readfile('BerndKrueger/Mozart/mz_332_1.mid')),
    ( "Sonate Nr. 12 F-Dur, KV 332, 2. Satz - Adagio",
      (SELECT id from composer WHERE surname='Mozart'),
      readfile('BerndKrueger/Mozart/mz_332_2.mid')),
    ( "Sonate Nr. 12 F-Dur, KV 332, 3. Satz - Assai allegro",
      (SELECT id from composer WHERE surname='Mozart'),
      readfile('BerndKrueger/Mozart/mz_332_3.mid')),
    ( "Sonate Nr. 13 B-Dur, KV 333, 1. Satz - Allegro",
      (SELECT id from composer WHERE surname='Mozart'),
      readfile('BerndKrueger/Mozart/mz_333_1.mid')),
    ( "Sonate Nr. 13 B-Dur, KV 333, 2. Satz - Andante cantabile",
      (SELECT id from composer WHERE surname='Mozart'),
      readfile('BerndKrueger/Mozart/mz_333_2.mid')),
    ( "Sonate Nr. 13 B-Dur, KV 333, 3. Satz - Allegretto grazioso",
      (SELECT id from composer WHERE surname='Mozart'),
      readfile('BerndKrueger/Mozart/mz_333_3.mid')),
    ( "Sonate Nr. 16 C-Dur (Sonata facile) , KV 545, 1. Satz - Allegro",
      (SELECT id from composer WHERE surname='Mozart'),
      readfile('BerndKrueger/Mozart/mz_545_1.mid')),
    ( "Sonate Nr. 16 C-Dur (Sonata facile) , KV 545, 2. Satz - Andante",
      (SELECT id from composer WHERE surname='Mozart'),
      readfile('BerndKrueger/Mozart/mz_545_2.mid')),
    ( "Sonate Nr. 16 C-Dur (Sonata facile) , KV 545, 3. Satz - Rondo Allegretto",
      (SELECT id from composer WHERE surname='Mozart'),
      readfile('BerndKrueger/Mozart/mz_545_3.mid')),
    ( "Sonate Nr. 17 B-Dur, KV 570, 1. Satz - Allegro",
      (SELECT id from composer WHERE surname='Mozart'),
      readfile('BerndKrueger/Mozart/mz_570_1.mid')),
    ( "Sonate Nr. 17 B-Dur, KV 570, 2. Satz - Adagio",
      (SELECT id from composer WHERE surname='Mozart'),
      readfile('BerndKrueger/Mozart/mz_570_2.mid')),
    ( "Sonate Nr. 17 B-Dur, KV 570, 3. Satz - Allegretto",
      (SELECT id from composer WHERE surname='Mozart'),
      readfile('BerndKrueger/Mozart/mz_570_3.mid')),

    ( "Prélude C# minor, Opus 3/2, Lento - Agitato",
      (SELECT id from composer WHERE surname='Rachmaninow'),
      readfile('BerndKrueger/Rachmaninow/rac_op3_2_format0.mid')),
    ( "10 Préludes, Opus 23, No. 2 - Maestoso",
      (SELECT id from composer WHERE surname='Rachmaninow'),
      readfile('BerndKrueger/Rachmaninow/rac_op23_2_format0.mid')),
    ( "10 Préludes, Opus 23, No. 3 - Tempo di Minuetto",
      (SELECT id from composer WHERE surname='Rachmaninow'),
      readfile('BerndKrueger/Rachmaninow/rac_op23_3_format0.mid')),
    ( "10 Préludes, Opus 23, No. 5 - Alla marcia",
      (SELECT id from composer WHERE surname='Rachmaninow'),
      readfile('BerndKrueger/Rachmaninow/rac_op23_5_format0.mid')),
    ( "10 Préludes, Opus 23, No. 7 - Allegro",
      (SELECT id from composer WHERE surname='Rachmaninow'),
      readfile('BerndKrueger/Rachmaninow/rac_op23_7_format0.mid')),
    ( "13 Préludes, Opus 32, No. 1 - Allegro vivace",
      (SELECT id from composer WHERE surname='Rachmaninow'),
      readfile('BerndKrueger/Rachmaninow/rac_op32_1_format0.mid')),
    ( "13 Préludes, Opus 32, No. 13 - Grave",
      (SELECT id from composer WHERE surname='Rachmaninow'),
      readfile('BerndKrueger/Rachmaninow/rac_op32_13_format0.mid')),
    ( "8 Études-tableaux, Opus 33, No. 5 - Non allegro - Presto",
      (SELECT id from composer WHERE surname='Rachmaninow'),
      readfile('BerndKrueger/Rachmaninow/rac_op33_5_format0.mid')),
    ( "8 Études-tableaux, Opus 33, No. 6 - Allegro con fuoco",
      (SELECT id from composer WHERE surname='Rachmaninow'),
      readfile('BerndKrueger/Rachmaninow/rac_op33_6_format0.mid')),
    ( "8 Études-tableaux, Opus 33, No. 8 - Grave",
      (SELECT id from composer WHERE surname='Rachmaninow'),
      readfile('BerndKrueger/Rachmaninow/rac_op33_8_format0.mid'));
