[Default]
version = 0.9.4
edition = Salieri

[Settings]
tempo = 1
transposition = 0
dynamics = 50

[Network]
piano_daemon_websocket_port = 1770
backend_rest_api_port = 5000
frontend_server_port = 8080

